apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api-app
  labels:
    app: demo-api-app
    type: server
spec:
  replicas: 2
  selector:
    matchLabels:
      name: node-api-app
      tier: server
  template:
    metadata:
      labels:
        name: node-api-app
        tier: server
    spec:
      containers:
        - name: node-api-app
          image: dheeraj1429/node-demo-api:v3
          imagePullPolicy: Always
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: PORT
            - name: SECRET
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
            initialDelaySeconds: 5
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          volumeMounts:
            - mountPath: /app/dist/task
              name: task
      volumes:
        - name: task
          persistentVolumeClaim:
            claimName: host-persistent-volume-claim
