apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  volumeName: host-pv
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
