apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    name: node-api-app
    tier: server
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  type: LoadBalancer
